package au.com.evonet.nat20.pf2e.core

import kotlinx.serialization.Serializable

/**
 * A Pathfinder 2e ability-score **build** — the ordered record of boosts and
 * flaws that produced a character's scores, kept re-editable (the PF2e analogue
 * of the 2024 edition's `baseAbilityScores` + advancement record). Scores are
 * generated by applying, in order: ancestry (fixed + free boosts, and a flaw) →
 * background (one of two + a free boost) → class (key ability) → four free boosts.
 *
 * Two rules make order + grouping matter: a boost is **+2** but only **+1** once
 * the score is **18+** (the late free boosts hit that wall most), and you may not
 * boost the same ability twice *within a step*. Port of iOS `AbilityBuild`.
 */
@Serializable
data class AbilityBuild(
    /** Abilities taking a −2 flaw (applied before boosts). */
    val flaws: List<PfAbility> = emptyList(),
    /** Boosts grouped by step, applied in order; the no-duplicate rule is per step. */
    val boostSteps: List<List<PfAbility>> = emptyList(),
) {
    /** Fold flaws + boost steps onto [base] (all 10s by default), honouring +2/+1-at-18 per boost in order. */
    fun resolved(base: PfAbilityScores = PfAbilityScores()): PfAbilityScores {
        var scores = base
        for (flaw in flaws) scores = scores.with(flaw, scores.score(flaw) - 2)
        for (step in boostSteps) {
            for (ability in step) {
                val current = scores.score(ability)
                scores = scores.with(ability, current + if (current >= 18) 1 else 2)
            }
        }
        return scores
    }

    /** True if any single step boosts the same ability more than once — the one rule a legal build must not break. */
    val hasDuplicateBoostInAStep: Boolean get() = boostSteps.any { step -> step.toSet().size != step.size }
}
